make the installer more friendly

diff --git a/bin/mway b/bin/mway
--- a/bin/mway
+++ b/bin/mway
@@ -1,6 +1,9 @@
 #!/bin/sh
 
-PROJECT_NAME=$1 # First argument passed
+if [ -d .git/ ]; then
+  echo "Error - you are inside a git repo.  This is almost certainly not where you want to be."
+  exit 1
+fi
 
 function create_new_project {  
   git clone git@github.com:michaelparenteau/myway $PROJECT_NAME &&
@@ -21,6 +24,29 @@ function init_git {
   git add . &&
   git ci -am "first commit"
 }
+
+function display_usage {
+  local project_name=$1
+  
+  if [ -z $project_name ] ; then
+    echo "Usage: $0 <new project name>"
+    exit 1
+  fi
+}
+
+function check_that_directory_does_not_already_exist {
+  local project_name=$1
+
+  if [ -d $project_name ]; then
+    echo "A directory named $project_name already exists.  Use a different name."
+    exit 1
+  fi
+}
+
+PROJECT_NAME=$1 # First argument passed
+
+display_usage $PROJECT_NAME
+check_that_directory_does_not_already_exist $PROJECT_NAME
 
 create_new_project &&
 setup_rvmrc &&
